# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doc.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdoc.proto\x12\x13\x46\x61lcon.IndexFactory\"!\n\x0cIntEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x05\"#\n\x0e\x46loatEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x02\"9\n\tRangeInfo\x12\x10\n\x08range_id\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x03\"m\n\x08TermInfo\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\r\n\x05\x65xtra\x18\x02 \x01(\x08\x12\r\n\x05index\x18\x03 \x01(\x08\x12\x15\n\x0buint32Value\x18\x04 \x01(\rH\x00\x12\x15\n\x0buint64Value\x18\x05 \x01(\x04H\x00\x42\x07\n\x05value\"\xe5\x01\n\x07Section\x12\x30\n\ttermInfos\x18\x01 \x03(\x0b\x32\x1d.Falcon.IndexFactory.TermInfo\x12:\n\x0fint32_embedding\x18\x02 \x03(\x0b\x32!.Falcon.IndexFactory.IntEmbedding\x12<\n\x0f\x66loat_embedding\x18\x03 \x03(\x0b\x32#.Falcon.IndexFactory.FloatEmbedding\x12.\n\x06ranges\x18\x04 \x03(\x0b\x32\x1e.Falcon.IndexFactory.RangeInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTEMBEDDING']._serialized_start=34
  _globals['_INTEMBEDDING']._serialized_end=67
  _globals['_FLOATEMBEDDING']._serialized_start=69
  _globals['_FLOATEMBEDDING']._serialized_end=104
  _globals['_RANGEINFO']._serialized_start=106
  _globals['_RANGEINFO']._serialized_end=163
  _globals['_TERMINFO']._serialized_start=165
  _globals['_TERMINFO']._serialized_end=274
  _globals['_SECTION']._serialized_start=277
  _globals['_SECTION']._serialized_end=506
# @@protoc_insertion_point(module_scope)
