package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "trans_number",
    srcs = [
        "trans_number.cpp",
    ],
    hdrs = [
        "trans_number.h",
    ],
    deps = [
        "//src/utils:npur_log",
        "//huawei_platform:huaweiSecureC",
    ],
    alwayslink = True,
)